name: Continuous Integration

on:
  push:
    branches:
      - master
      - feature*
      - hotfix*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 0: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 1: Pruebas de SAST
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      # Paso 2: Crear archivo de credenciales
      - name: Crear archivo de credenciales
        run: |
          echo "[credentials]" > credentials.ini
          echo "username=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini
        shell: bash

      # Paso 3: Construcción de Docker
      - name: Build docker image
        run: |
          docker build -t devops_ws . --tag devops_ws:$(date +%s)